name: GHA Playground

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup workflow
    outputs:
      potato_matrix: ${{ steps.export-matrix.outputs.potato_matrix }}
      tomato_matrix: ${{ steps.export-matrix.outputs.tomato_matrix }}

    steps:
      - name: Setup Options
        id: setup-options
        run: |
          echo potato_option=1 >> ${GITHUB_OUTPUT}
          echo tomato_option=2 >> ${GITHUB_OUTPUT}

      - name: Setup matrix
        id: export-matrix
        env:
          POTATO_MATRIX: >-
            {
              "include": [
                  {
                      "target": "potato",
                      "option": "option1",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  },
                  {
                      "target": "potato",
                      "option": "option2",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option6",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option7",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option8",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option9",
                      "cc_option": ${{ steps.setup-options.outputs.potato_option }}
                  }
              ]
            }
          TOMATO_MATRIX: >-
            {
              "include": [
                  {
                      "target": "tomato",
                      "option": "option3",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  },
                  {
                      "target": "tomato",
                      "option": "option4",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option6",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option7",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option8",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  },
                  {
                      "target": "cucumber",
                      "option": "option9",
                      "cc_option": ${{ steps.setup-options.outputs.tomato_option }}
                  }
              ]
            }
        run: |
          echo potato_matrix=$(jq -r -c '.' <<< ${POTATO_MATRIX}) >> ${GITHUB_OUTPUT}
          echo tomato_matrix=$(jq -r -c '.' <<< ${TOMATO_MATRIX}) >> ${GITHUB_OUTPUT}

  echo-potato:
    needs: [setup]
    uses: ./.github/workflows/echo.yml
    with:
      host: potato
      matrix: ${{ needs.setup.outputs.potato_matrix }}

  echo-tomato:
    needs: [setup]
    uses: ./.github/workflows/echo.yml
    with:
      host: tomato
      matrix: ${{ needs.setup.outputs.tomato_matrix }}

